name: Docker container deployment

on:
  push:
    branches: ["main"]

jobs:
  Build-Docker-Container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: build/Dockerfile
          push: true
          tags: operationxen/moonsea_codex_api:main

  Deploy-To-Server:
    runs-on: ubuntu-latest
    needs: Build-Docker-Container

    steps:
      - name: Connect to target
        run: echo "do the thing"
